In [12]:
from tanalysis import improcess, tracking, stitching, traj_analysis
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import napari

In [2]:
og_dirname = r"D:\pcanaleta\Thunder\SpinningDisk_Test\CD8-Treg\APC_WT\Originals\CD8_WT_APC_Thunder.lif"

imgs, names, _ = improcess.imread(og_dirname, False, False)

lab_img = improcess.label_cells(imgs[0], 1, )

In [ ]:
plt.figure()
plt.imshow(lab_img[0][0], cmap="nipy_spectral")
plt.show()

In [3]:
tracks = tracking.track_labeled_video(lab_img, 50, 6)

In [4]:
print(tracks)

[{'track_id': 28, 'entries': [TrackEntry(frame=0, label=28, centroid=(0.5858585858585859, 882.2676767676768, 33.125)), TrackEntry(frame=1, label=27, centroid=(0.4936548223350254, 883.5215736040609, 27.730964467005077)), TrackEntry(frame=2, label=27, centroid=(0.46142208774583965, 884.3449319213313, 19.388804841149774)), TrackEntry(frame=3, label=24, centroid=(0.437984496124031, 882.5174418604652, 12.358527131782946)), TrackEntry(frame=4, label=21, centroid=(0.4978165938864629, 882.2489082969432, 7.091703056768559)), TrackEntry(frame=5, label=65, centroid=(6.75, 865.9285714285714, 15.071428571428571))]}, {'track_id': 66, 'entries': [TrackEntry(frame=0, label=66, centroid=(9.087346024636059, 756.7446808510638, 500.8376259798432)), TrackEntry(frame=1, label=74, centroid=(9.37948717948718, 756.0666666666667, 499.4307692307692)), TrackEntry(frame=2, label=65, centroid=(9.292508917954816, 754.8917954815696, 497.5231866825208)), TrackEntry(frame=3, label=67, centroid=(9.471794871794872, 753.3

In [7]:
sum_tracks = tracking.summarize_track(tracks[0])
print(sum_tracks['centroids'])

[[5.85858586e-01 8.82267677e+02 3.31250000e+01]
 [4.93654822e-01 8.83521574e+02 2.77309645e+01]
 [4.61422088e-01 8.84344932e+02 1.93888048e+01]
 [4.37984496e-01 8.82517442e+02 1.23585271e+01]
 [4.97816594e-01 8.82248908e+02 7.09170306e+00]
 [6.75000000e+00 8.65928571e+02 1.50714286e+01]]


In [10]:
det_tracks = []
for i in range(len(tracks)):
    for entry in tracks[i]['entries']:
        det_tracks.append(sum_tracks['centroids'])

In [15]:
viewer = napari.Viewer()
viewer.add_image(imgs[0], name=names[0])
viewer.add_labels(lab_img, name="labels")
viewer.add_tracks(np.asarray(det_tracks))

ValueError: track vertices should be a NxD array